# Generated by Django 5.2.8 on 2025-11-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('joining_date', models.DateField()),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('teacher_image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
            ],
        ),
    ]
