# Generated by Django 5.2.8 on 2025-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_class', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Scheduled', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
