# Generated by Django 5.2.8 on 2025-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_sports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostel_name', models.CharField(max_length=200)),
                ('hostel_type', models.CharField(max_length=100)),
                ('total_rooms', models.IntegerField()),
            ],
        ),
    ]
